### PR TITLE
Encrypted Memos

### PR DESCRIPTION
**Pull request by garbageslam**
A proposal to add encrypted memos to transaction outputs

[Rendered RFC](https://github.com/garbageslam/mcips/blob/encrypted-memos/text/0003-encrypted-memos.md)

### CODE REVIEW

**Review by eranrund — APPROVED** [review]
Nice!

**Comment by jcape** [comment]
Nit: the file should be 0003-foo, to match the PR number.

**Comment by garbageslam** [comment]
Feel free to join discussion in discord:

https://discord.gg/TTQ5mE37

**Review by mfaulk — APPROVED** [review]
This looks great

**Review by jcape — APPROVED** [review]
LGTM.

**Comment by garbageslam** [comment]
This proposal is now entering the Final Comment Period

**Comment by garbageslam** [comment]
We are delaying the Final Comment Period because of questions raised here: https://github.com/mobilecoinfoundation/mobilecoin/issues/905#issuecomment-920146898

We have updated the document to reflect our updated plans for actually releasing the change, including the interim period during which memos are optional, to ease the upgrade path, and the rationale for this.

If there are no further comments then we will likely try to enter a final comment period starting tomorrow.

**Comment by garbageslam** [comment]
This is entering the Final Comment Period again

**Pull request merged**
